apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
        - name: init-loki-dirs
          image: busybox
          command:
            - sh
            - -c
            - mkdir -p /wal /loki/chunks /loki/index /loki/cache /loki/compactor && chmod -R 777 /wal /loki
          volumeMounts:
            - name: wal
              mountPath: /wal
            - name: loki
              mountPath: /loki

      containers:
        - name: loki
          image: grafana/loki:2.8.2
          args: ["-config.file=/etc/loki/local-config.yaml"]
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: wal
              mountPath: /wal
            - name: loki
              mountPath: /loki

      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: wal
          emptyDir: {}
        - name: loki
          emptyDir: {}
