apiVersion: apps/v1
kind: Deployment
metadata:
  name: otelcol
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otelcol
  template:
    metadata:
      labels:
        app: otelcol
    spec:
      containers:
        - name: otelcol
          image: otel/opentelemetry-collector-contrib:0.76.1
          args: ["--config=/etc/otelcol/otel-config.yaml"]
          ports:
            - containerPort: 3500
          volumeMounts:
            - name: config
              mountPath: /etc/otelcol
      volumes:
        - name: config
          configMap:
            name: otelcol-config
